// src/stores/mockData/contractors.ts
import type { OrganizationContractor } from '@/types';

export const mockContractors: OrganizationContractor[] = [
  {
    id: 'contractor-1',
    tenantId: 'tenant-1',
    contractorExternalOrgId: 'ext-org-1',
    contractorName: 'УЦ "Профессионал"',
    contractorInn: '7701234567',
    type: 'training_center',
    services: ['full_training', 'certification'],
    contractNumber: 'Д-2024-001',
    contractDate: '2024-01-15',
    contractExpiryDate: '2024-12-31',
    contactPerson: 'Сидорова Елена Петровна',
    contactPhone: '+7 (495) 123-45-67',
    contactEmail: 'info@professional.ru',
    status: 'active',
    notes: 'Основной партнер по обучению промышленной безопасности',
    createdAt: new Date(Date.now() - 300 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString()
  },
  {
    id: 'contractor-2',
    tenantId: 'tenant-1',
    contractorExternalOrgId: 'ext-org-2',
    contractorName: 'Центр охраны труда',
    contractorInn: '7702345678',
    type: 'training_center',
    services: ['full_training', 'sdo_access_only'],
    contractNumber: 'Д-2024-002',
    contractDate: '2024-02-01',
    contractExpiryDate: '2025-01-31',
    contactPerson: 'Иванов Петр Сергеевич',
    contactPhone: '+7 (495) 234-56-78',
    contactEmail: 'ot@center.ru',
    status: 'active',
    notes: 'Обучение по охране труда + доступ к СДО',
    createdAt: new Date(Date.now() - 270 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString()
  },
  {
    id: 'contractor-3',
    tenantId: 'tenant-1',
    contractorExternalOrgId: 'ext-org-5',
    contractorName: 'Академия безопасности',
    contractorInn: '7705678901',
    type: 'training_center',
    services: ['full_training', 'certification', 'consulting'],
    contractNumber: 'Д-2024-005',
    contractDate: '2024-03-10',
    contractExpiryDate: '2025-03-09',
    contactPerson: 'Смирнова Ольга Викторовна',
    contactPhone: '+7 (495) 567-89-01',
    contactEmail: 'info@safety-academy.ru',
    status: 'active',
    notes: 'Комплексное обучение + консультирование по ПБ',
    createdAt: new Date(Date.now() - 200 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString()
  },
  {
    id: 'contractor-4',
    tenantId: 'tenant-1',
    contractorExternalOrgId: 'ext-org-6',
    contractorName: 'ООО "СтройМонтаж"',
    contractorInn: '7706789012',
    type: 'contractor',
    services: [],
    contractNumber: 'ПД-2024-010',
    contractDate: '2024-01-20',
    contractExpiryDate: '2024-12-20',
    contactPerson: 'Волков Сергей Петрович',
    contactPhone: '+7 (495) 678-90-12',
    contactEmail: 'info@stroymontazh.ru',
    status: 'active',
    notes: 'Строительно-монтажные работы на объектах',
    createdAt: new Date(Date.now() - 280 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString()
  },
  {
    id: 'contractor-5',
    tenantId: 'tenant-1',
    contractorName: 'Учебно-курсовой комбинат',
    contractorInn: '7704567890',
    type: 'training_center',
    services: ['full_training'],
    contractNumber: 'Д-2023-015',
    contractDate: '2023-06-01',
    contractExpiryDate: '2024-05-31',
    contactPerson: 'Кузнецов Михаил Иванович',
    contactPhone: '+7 (495) 456-78-90',
    contactEmail: 'info@ukk.ru',
    status: 'suspended',
    notes: 'Договор приостановлен из-за истечения срока',
    createdAt: new Date(Date.now() - 360 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString()
  }
];
