// src/stores/mockData/externalOrganizations.ts
import type { ExternalOrganization } from '@/types';

export const mockExternalOrganizations: ExternalOrganization[] = [
  {
    id: 'ext-org-1',
    tenantId: 'tenant-1',
    type: 'training_center',
    name: 'УЦ "Профессионал"',
    inn: '7701234567',
    contactPerson: 'Сидорова Елена Петровна',
    phone: '+7 (495) 123-45-67',
    email: 'info@professional.ru',
    address: 'г. Москва, ул. Ленина, д. 10',
    website: 'https://professional.ru',
    accreditations: ['Ростехнадзор', 'Минтруд'],
    description: 'Образовательная организация, специализирующаяся на обучении по промышленной безопасности',
    status: 'active',
    createdAt: new Date(Date.now() - 365 * 24 * 60 * 60 * 1000).toISOString()
  },
  {
    id: 'ext-org-2',
    tenantId: 'tenant-1',
    type: 'training_center',
    name: 'Центр охраны труда',
    inn: '7702345678',
    contactPerson: 'Иванов Петр Сергеевич',
    phone: '+7 (495) 234-56-78',
    email: 'ot@center.ru',
    address: 'г. Москва, пр-т Мира, д. 25',
    accreditations: ['Минтруд'],
    description: 'Обучение по охране труда и промышленной безопасности',
    status: 'active',
    createdAt: new Date(Date.now() - 300 * 24 * 60 * 60 * 1000).toISOString()
  },
  {
    id: 'ext-org-3',
    tenantId: 'tenant-1',
    type: 'training_center',
    name: 'Энергетический центр',
    inn: '7703456789',
    contactPerson: 'Петрова Анна Сергеевна',
    phone: '+7 (495) 345-67-89',
    email: 'info@energycenter.ru',
    address: 'г. Москва, ул. Энергетическая, д. 12',
    description: 'Специализированное обучение для энергетиков',
    status: 'active',
    createdAt: new Date(Date.now() - 250 * 24 * 60 * 60 * 1000).toISOString()
  },
  {
    id: 'ext-org-4',
    tenantId: 'tenant-1',
    type: 'training_center',
    name: 'Учебно-курсовой комбинат',
    inn: '7704567890',
    contactPerson: 'Кузнецов Михаил Иванович',
    phone: '+7 (495) 456-78-90',
    email: 'info@ukk.ru',
    address: 'г. Москва, ул. Обучения, д. 5',
    accreditations: ['Минобразования'],
    description: 'Подготовка и переподготовка рабочих кадров',
    status: 'active',
    createdAt: new Date(Date.now() - 200 * 24 * 60 * 60 * 1000).toISOString()
  },
  {
    id: 'ext-org-5',
    tenantId: 'tenant-1',
    type: 'training_center',
    name: 'Академия безопасности',
    inn: '7705678901',
    contactPerson: 'Смирнова Ольга Викторовна',
    phone: '+7 (495) 567-89-01',
    email: 'info@safety-academy.ru',
    address: 'г. Москва, пр. Безопасности, д. 20',
    website: 'https://safety-academy.ru',
    accreditations: ['Ростехнадзор', 'Минтруд', 'МЧС'],
    description: 'Комплексное обучение по всем видам безопасности',
    status: 'active',
    createdAt: new Date(Date.now() - 180 * 24 * 60 * 60 * 1000).toISOString()
  },
  {
    id: 'ext-org-6',
    tenantId: 'tenant-1',
    type: 'contractor',
    name: 'ООО "СтройМонтаж"',
    inn: '7706789012',
    kpp: '770601001',
    contactPerson: 'Волков Сергей Петрович',
    phone: '+7 (495) 678-90-12',
    email: 'info@stroymontazh.ru',
    address: 'г. Москва, ул. Строительная, д. 30',
    description: 'Подрядная организация по строительно-монтажным работам',
    status: 'active',
    createdAt: new Date(Date.now() - 150 * 24 * 60 * 60 * 1000).toISOString()
  },
  {
    id: 'ext-org-7',
    tenantId: 'tenant-1',
    type: 'regulatory_body',
    name: 'Ростехнадзор',
    contactPerson: 'Государственная инспекция',
    phone: '+7 (495) 987-65-43',
    email: 'info@gosnadzor.ru',
    address: 'г. Москва, ул. Таганская, д. 34',
    website: 'https://gosnadzor.ru',
    description: 'Федеральная служба по экологическому, технологическому и атомному надзору',
    status: 'active',
    createdAt: new Date(Date.now() - 400 * 24 * 60 * 60 * 1000).toISOString()
  }
];