import { lazy } from 'react';

export const LoginPage = lazy(() => import("@/modules/auth").then(m => ({ default: m.LoginPage })));
export const DashboardPage = lazy(() => import("@/modules/dashboard").then(m => ({ default: m.DashboardPage })));
export const TenantsPage = lazy(() => import("@/modules/tenants").then(m => ({ default: m.TenantsPage })));
export const SettingsPage = lazy(() => import("@/modules/settings").then(m => ({ default: m.SettingsPage })));
export const CatalogPage = lazy(() => import("@/modules/catalog").then(m => ({ default: m.CatalogPage })));
export const ContractorsPage = lazy(() => import("@/modules/catalog/pages/ContractorsPage"));
export const IncidentsPage = lazy(() => import("@/modules/incidents").then(m => ({ default: m.IncidentsPage })));
export const ChecklistsPage = lazy(() => import("@/modules/checklists").then(m => ({ default: m.ChecklistsPage })));
export const AttestationPage = lazy(() => import("@/modules/attestation").then(m => ({ default: m.AttestationPage })));
export const TasksPage = lazy(() => import("@/modules/tasks").then(m => ({ default: m.TasksPage })));
export const ExaminationPage = lazy(() => import("@/modules/examination").then(m => ({ default: m.ExaminationPage })));
export const NotificationsPage = lazy(() => import("@/modules/notifications").then(m => ({ default: m.NotificationsPage })));
export const CreateNotificationPage = lazy(() => import("@/modules/notifications/pages/CreateNotificationPage"));
export const NotificationsHistoryPage = lazy(() => import("@/modules/notifications/pages/NotificationsHistoryPage"));
export const MaintenancePage = lazy(() => import("@/modules/maintenance").then(m => ({ default: m.MaintenancePage })));
export const BudgetPage = lazy(() => import("@/modules/budget").then(m => ({ default: m.BudgetPage })));
export const TrainingCenterPage = lazy(() => import("@/modules/training-center/pages/TrainingCenterPage"));
export const KnowledgeBasePage = lazy(() => import("@/modules/knowledge-base").then(m => ({ default: m.KnowledgeBasePage })));
export const AuditPage = lazy(() => import("@/modules/audit").then(m => ({ default: m.AuditPage })));
export const NotFoundPage = lazy(() => import("@/modules/common").then(m => ({ default: m.NotFoundPage })));